# Generated by Django 5.1.6 on 2025-02-19 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_categorys_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantoptions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categorys'),
        ),
    ]
