# Generated by Django 5.1.6 on 2025-02-24 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_products_created_by_store_products_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.store'),
            preserve_default=False,
        ),
    ]
