# Generated by Django 5.1.6 on 2025-02-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_variantoptions_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='productvariants',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productvariants',
            old_name='variants_id',
            new_name='variants',
        ),
        migrations.RenameField(
            model_name='variants',
            old_name='variant_options_id',
            new_name='variant_options',
        ),
        migrations.RenameField(
            model_name='variants',
            old_name='variant_values_id',
            new_name='variant_values',
        ),
    ]
