# Generated by Django 5.1.6 on 2025-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
