# Generated by Django 5.1.6 on 2025-02-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_store_monthly_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
    ]
