# Generated by Django 5.1.6 on 2025-02-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_rename_price_orderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ecommerce.productvariants'),
            preserve_default=False,
        ),
    ]
