# Generated by Django 5.1.6 on 2025-02-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_store_total_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('cancel_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_records', to='ecommerce.order')),
            ],
        ),
    ]
