# Generated by Django 5.1.6 on 2025-02-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_ordercancelrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
