# Generated by Django 5.1.6 on 2025-02-21 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_productvariants_stock'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart_item',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cartitem'),
            preserve_default=False,
        ),
    ]
