# Generated by Django 5.1.6 on 2025-02-21 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_productvariants_stock'),
        ('payment', '0002_payment_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cartitem'),
        ),
    ]
