# Generated by Django 5.1.6 on 2025-02-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_productvariants_stock'),
        ('payment', '0003_alter_payment_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_item',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='ecommerce.orderitem'),
            preserve_default=False,
        ),
    ]
