# Generated by Django 5.1.6 on 2025-02-21 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_productvariants_stock'),
        ('payment', '0004_payment_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart_item',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='ecommerce.orderitem'),
        ),
    ]
