# Generated by Django 5.1.6 on 2025-02-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_payment_cart_item_alter_payment_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
